config/routes.rb
Sen2::Application.routes.draw do

  root 'blogs#index'

  get 'contact' => 'static#contact'
  get 'test' => 'static#test'
  get 'admin' => 'admin#index'
  get 'pricelist' => 'pricelist#index'

  resources :blogs, :users, :headers, :active_headers

  resources :artworks,:categories do
    collection do
      post :sort
    end
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/active_header.rb
class ActiveHeader < ActiveRecord::Base
	belongs_to :header
end

app/controllers/active_headers_controller.rb
class ActiveHeadersController < ApplicationController
  before_action :set_active_header, only: [:show, :edit, :update, :destroy]

  # GET /active_headers
  def index
    @active_headers = ActiveHeader.all
  end

  # GET /active_headers/1
  def show
  end

  # GET /active_headers/new
  def new
    @active_header = ActiveHeader.new
    @headers = Header.all
  end

  # GET /active_headers/1/edit
  def edit
    @headers = Header.all
  end

  # POST /active_headers
  def create
    @active_header = ActiveHeader.new(active_header_params)

    if @active_header.save
      redirect_to @active_header, notice: 'Active header was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /active_headers/1
  def update
    if @active_header.update(active_header_params)
      redirect_to admin_url, notice: 'Active header was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /active_headers/1
  def destroy
    @active_header.destroy
    redirect_to active_headers_url, notice: 'Active header was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_active_header
      @active_header = ActiveHeader.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def active_header_params
      params.require(:active_header).permit(:header_id)
    end
end

app/views/active_headers/_activeheader.html.haml
- ActiveHeader.where(id: 1).each do |active|
  = image_tag active.header.image_url(:large), class: 'header-img'

app/views/active_headers/_form.html.haml
= form_for(@active_header) do |f|
  - if @active_header.errors.any?
    #error_explanation
      #h2= pluralize(@header.errors.count, "error") + 'prohibited this category from being saved'
      %ul
        -@active_header.errors.full_messages.each do |msg|
          %li= msg

  %table#headers
    - @headers.each do |header|
      %tr
        %td
          =image_tag header.image_url(:large), width: '100%'
        %td.actions
          =f.radio_button :header_id, header.id

  .actions
    = f.submit class: 'btn'
    = link_to 'New Header', new_header_path, class: 'btn'

app/views/active_headers/edit.html.haml
%section.admin
  %h1 Update Header
  = render 'form'

app/views/active_headers/index.html.haml
%h1 Listing active_headers

%table
  %thead
    %tr
      %th Id
      %th

  %tbody
    - @active_headers.each do |active_header|
      %tr
        %td= active_header.header_id
        %td.actions
          = link_to 'Show', active_header
          = link_to 'Edit', edit_active_header_path(active_header)
          = link_to 'Destroy', active_header, method: :delete, data: { confirm: 'Are you sure?' }


= link_to 'New Active header', new_active_header_path

app/views/active_headers/new.html.haml
%section.admin
  %h1 New Active Header
  = render 'form'

app/views/active_headers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @active_header.id %>
</p>

<%= link_to 'Edit', edit_active_header_path(@active_header) %> |
<%= link_to 'Back', active_headers_path %>