config/routes.rb
Sen2::Application.routes.draw do

  root 'blogs#index'

  get 'contact' => 'static#contact'
  get 'test' => 'static#test'
  get 'admin' => 'admin#index'
  get 'pricelist' => 'pricelist#index'

  resources :blogs, :users, :headers, :active_headers

  resources :artworks,:categories do
    collection do
      post :sort
    end
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :artworks

  validates :name, presence: true

  before_destroy :ensure_category_has_no_artwork

  private
  
  def ensure_category_has_no_artwork
    if artworks.empty?
      return true 
    else
      errors.add(:base, 'Artwork present')
      return false
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  skip_before_filter :authorize, only: [:show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.order("position")
  end

  def show
    @artworks = @category.artworks.order("position")
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: 'Category successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category successfully destroyed.'
  end

  def sort
    params[:category].each_with_index do |id, index|
      Category.where(id: id).update_all(position: index+1)
    end
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name, :hidden, :position)
    end
end

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  - if @category.errors.any?
    #error_explanation
      #h2= pluralize(@category.errors.count, "error") + 'prohibited this category from being saved'
      %ul
        -@category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, autofocus: 'autofocus'
  .field
    = f.label :hidden
    = f.check_box :hidden
  .actions
    = f.submit class: 'btn'

app/views/categories/_listcats.html.haml
- Category.order("position").each do |category|
  -if !category.hidden
    %li= link_to category.name, category, class: cp(category)

app/views/categories/edit.html.haml
%section.admin
  %h1 Editing category
  = render 'form'

app/views/categories/index.html.haml
%section.admin
  %h1 Listing categories

  %table
    %thead
      %tr
        %th Name
        %th Hidden
        %th
    %tbody.sorts{ data: { update_url: sort_categories_url } }
      - @categories.each do |category|
        = content_tag_for :tr, category do
          %td= category.name
          %td= category.hidden
          %td.actions
            = link_to 'Show', category
            = link_to 'Edit', edit_category_path(category)
            = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

  .actions
    = link_to 'New Category', new_category_path, class: 'btn'

app/views/categories/new.html.haml
%section.admin
  %h1 New category
  = render 'form'

app/views/categories/show.html.haml
%ul.images
  - @artworks.each do |artwork|
    %li
      = link_to image_tag(artwork.image_url(:thumb).to_s, alt: artwork.title), artwork.image_url(:large).to_s, data: { sold: artwork.sold, title: artwork.title, year: artwork.year, width: artwork.width, length: artwork.length, medium: artwork.medium }, class: 'jerkbox'