config/routes.rb
Sen2::Application.routes.draw do

  root 'blogs#index'

  get 'contact' => 'static#contact'
  get 'test' => 'static#test'
  get 'admin' => 'admin#index'
  get 'pricelist' => 'pricelist#index'

  resources :blogs, :users, :headers, :active_headers

  resources :artworks,:categories do
    collection do
      post :sort
    end
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Jamie Hef
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    %link{ href: 'http://fonts.googleapis.com/css?family=Noto+Sans:400,700', rel: 'stylesheet', type: 'text/css' }
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    - if notice
      %p#notice= notice
    .container
      %header.main
        = render '/active_headers/activeheader'
        .pinned
          %h1= link_to 'Jamie Hef', root_path, class: cp(root_path)
          %nav#main-nav
            %ul
              %li= link_to 'Blog', blogs_path, class: cp(blogs_path)
              = render '/categories/listcats'
              %li= link_to 'Contact', contact_path, class: cp(contact_path)
      .content
        = yield
      - if session[:user_id]
        %nav#admin-nav
          %ul
            %li= link_to 'New Blog', new_blog_path
            %li= link_to 'New Artwork', new_artwork_path
            %li= link_to 'Sort Artworks', artworks_path
            %li= link_to 'Change Header', edit_active_header_path(1)
            %li= link_to 'Categories', categories_path
            %li= link_to 'Logout', logout_path, method: :delete, class: 'logout'